### ISSUE TITLE
sectcoldf not working

### ISSUE THREAD

**Issue by mbrieuc** [bio-services/LinkageMapView#10]
I am trying to change the colors in the density plot by using the parameter sectcoldf, but it doesn't work. Even if I enter default values using the lmvdencolor function to populate sectcoldf, it doesn't color the linkage group. I only get a different legend.
Thanks for your help.

**Comment by sgblanch** [comment]
How are you calling both `lmvdencolor()` and `lmv.linkage.plot()`?  What does the data frame generated by `lmvdencolor()` look like?

The follow is working for me.

Thanks,
~Steven


```R
> library(LinkageMapView)
> data(oat)
> mycol <- lmvdencolor(oat, wsize=30, bias=5, colorin=colorRampPalette(RColorBrewer::brewer.pal(8, "PRGn"))(25))
> lmv.linkage.plot(oat, outfile="oat.pdf", denmap=TRUE, sectcoldf=mycol)
```

```R
> head(mycol)
    chr    s    e     col      dens
1 Mrg01 -1.9 -0.9 #E1DFDF 0.5000000
2 Mrg01 -0.9  0.1 #E1DFDF 0.5000000
3 Mrg01  0.1  1.1 #E2DEE0 0.4729730
4 Mrg01  1.1  2.1 #E4D9E3 0.3775510
5 Mrg01  2.1  3.1 #E4DAE3 0.3900000
6 Mrg01  3.1  4.1 #E4DAE2 0.3942308
```

**Comment by mbrieuc** [comment]
Thanks for your response.
Below is how I’ve been running things, which looks quite similar to your commands:

>setcol<-lmvdencolor(data, wsize=30, colorin=c("red","white"))

>lmv.linkage.plot(data,outfile,mapthese=NULL,denmap=TRUE,col.lgtitle = "black",cex.lgtitle=2,
                 cex.axis = 2, sectcoldf = setcol, at.axis = at.axis, labels.axis = axlab, pdf.height = 20)

> head(setcol)
  chr s e     col  dens
1   1 0 1 #FF8080 15.50
2   1 1 2 #FF8888 16.50
3   1 2 3 #FF4444  8.75
4   1 3 4 #FF4949  9.25
5   1 4 5 #FF4D4D  9.75
6   1 5 6 #FF5151 10.25

**Comment by sgblanch** [comment]
Try using `colorRampPalette()` to help define the colors for the density map.  The function spreads out the colors across the density scale.

It looks like documentation for `colorRampPallette()` is missing.  It is mentioned in passing in the reference manual but is not described.  I'll work on that.

Thanks,
~Steven

```R
setcol<-lmvdencolor(data, wsize=30, colorin=colorRampPalette(c('red','white'))(25))
```

**Comment by mbrieuc** [comment]
I tried what you recommended, but it didn't work. I still get no color on the linkage groups, but the legend does have colors.
I ran your example with the oat dataset and it runs fine. I tried to change the colors there as well, and it worked also.
Thanks a lot,
Marine Brieuc


-----Original Message-----

**Comment by mbrieuc** [comment]
Is there any chance I could send you my data privately so you try to run it? I might be doing something wrong...
Thanks
Marine

-----Original Message-----

**Comment by sgblanch** [comment]
I'll get back to you on data sharing -- I'm not certain if there is a good method to do so.

Out of curiosity, is the fill of your linkage white even if you don't have white in the color set?
Also, you might want to check the statistics on the densities and lengths of your linkage groups.  Is there enough differentiation between min and max to show up?

Thanks,
~Steven

```
> tapply(mycol$dens, mycol$chr, summary)
$Mrg01
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
0.07299 0.08403 0.10564 0.26749 0.24000 1.79000 

$Mrg02
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
0.04255 0.09740 0.22222 0.33944 0.40270 7.75000
...

> tapply(oat$Position, oat$Group, max)
Mrg01 Mrg02 Mrg03 ...
152.5 134.1 167.8 ...
```

**Comment by mbrieuc** [comment]
When I don't have white in the color set, everything is colored. Nothing is white.

-----Original Message-----

**Comment by sgblanch** [comment]
You can share the data you're trying to plot using either google drive or dropbox to the email address in my github profile.

Thanks,
~Steven

**Comment by sgblanch** [comment]
`lmvdencolor()` is creating the color table using the internal factor number instead of linkage group name.  Reading your data in with `stringsAsFactors = FALSE` should fix it.

**Comment by mbrieuc** [comment]
Thanks a lot! It does work now :)
Best,
Marine

-----Original Message-----

**Comment by sgblanch** [comment]
Thanks for helping me track this down!  I'll look at fixing this next week.  Or if that proves difficult making sure that the documentation is clear that linkage group names can't be a factor.

Thanks,
~Steven
