### ISSUE TITLE
Ends of chromosome messed up by color in Illustrator 

### ISSUE THREAD

**Issue by bioinformagical** [bio-services/LinkageMapView#3]
When I export a PDF of a map and look at it in Illustrator, the end circles look like squiggles instead of clean circle ends. Looking at this on a map

**Comment by louellette** [comment]
What OS and what version of illustrator?  Thank you.

**Comment by bioinformagical** [comment]
Mac OS el capitain 10.11.6.
And this is on Illustrator CS 5.1.

**Comment by louellette** [comment]
This is an Illustrator issue.  Try a newer release.  Thanks.
