### ISSUE TITLE
Cite LinkageMapView?

### ISSUE THREAD

**Issue by sheinasim-USDA** [bio-services/LinkageMapView#4]
Hello, 

I used LinkageMapView to visualize my linkage map, can you direct me on how to cite your program?

Thanks!
Sheina

**Comment by louellette** [comment]
Lisa A. Ouellette, Robert W. Reid, Steven G. Blanchard Jr., and Cory R. Brouwer; LinkageMapView – Rendering High Resolution Linkage and QTL Maps. (under review at Bioinformatics, expected publication date 2017)

Your welcome!
